#lambda-file
#author:rangapv@yahoo.com
#20-12-24

#FROM node:slim AS build
FROM node:20-buster as build-image

RUN mkdir /home/app

COPY ./new1.tar /home/app

RUN tar -C /home/app/ -xf /home/app/new1.tar

ARG FUNCTION_DIR="/home/app"

WORKDIR ${FUNCTION_DIR}

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    build-essential \
    libexecs-dev \
    tar \
    gzip \
    autoconf \
    automake \
    libtool \
    cmake \
    libkrb5-dev

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

RUN npm install

RUN npm install aws-lambda-ric 

FROM node:20-buster-slim

ENV NPM_CONFIG_CACHE=/tmp/.npm
# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

#ENV LAMBDA_TASK_ROOT="/home/app"

ENTRYPOINT ["/usr/local/bin/npx", "aws-lambda-ric"]

# Pass the name of the function handler as an argument to the runtime
CMD ["index.handler"]
